# Generated by Django 2.2.1 on 2019-05-11 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(default='Your header for content', max_length=80)),
                ('Text', models.TextField()),
                ('CodeSnippet', models.TextField(blank=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='content_images')),
                ('ExternalLink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(default=datetime.datetime.now)),
                ('EditDate', models.DateTimeField(blank=True, null=True)),
                ('Title', models.CharField(default='Your tile', max_length=30)),
                ('Upvotes', models.IntegerField(default=0)),
                ('Downvotes', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Category')),
                ('Content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendTime', models.DateTimeField()),
                ('Text', models.TextField()),
                ('Upvotes', models.IntegerField(default=0)),
                ('Downvotes', models.IntegerField(default=0)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread')),
            ],
        ),
    ]
