# Generated by Django 2.2.1 on 2019-05-11 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='CreateDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
